version: '3'
services:
  backend:
    image: node:18.13.0
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
    command: sh -c "npm install && npm start"
    depends_on:
      - database

  frontend:
    image: node:18.13.0
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

  database:
    image: mongo:4.2
    container_name: mongo_vouch
    ports:
      - 27017:27017
